### ISSUE TITLE
Project Scope Approval 

### ISSUE THREAD

**Issue by Jimbojones1** [Pineapple-Party/BedroomParty#1]
Bedroom Party 

INDEX 

default environment on login page and then the login is right in the center 
login + super short explanation or slogan 
raining pineapples - on login click 

ABOUT 

ENVIRONMENTS 
list
give a default environment - tropical 

DEFAULTS
5 defaults to choose from 
background image | playlist or song | background noise

**Comment by code-for-coffee** [comment]
@Jimbojones1 @SpookyCorridor approved! This is going to be great!
